modified Socket.c
to avoid the following error:
2bwt-lib/Socket.c: In function ‘Socket* SocketInitiateConnection(int, const char*)’:
2bwt-lib/Socket.c:152:23: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
     if (socketPath == '\0' || socketPath[0] == '\0')

changed to  if (socketPath == "\0" || socketPath[0] == '\0')


this line exists twice found by search